name: DailyRewards
main: PocketEssential\DailyRewards\Main
version: 1.0.0
api: 1.0.0
description: Give player rewards daily!


commands:
    dailyrewards:
        description: rewards daily
        usage: /dailyrewards