---
Claimed: You have claimed your reward! You can claim it again in 24 hours!
Already_Claimed: You have already claimed it!


# Varibles
# {player} - For the player name!
#
RewardCommand: give {player} 264 50

---
