---
Checking: Please wait while we check if you have not already claimed your reward
Claimed: You have claimed your reward! You can claim it again in 24 hours
Already_Claimed: You have already claimed it! Please wait


# Varibles
# {player} - For the player name!
#
RewardCommand: give {player} 264 50

---
